name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f docker-test-env/Dockerfile -t qa-test-tagging:latest .
        
      - name: Run tests
        run: docker run --rm qa-test-tagging:latest